// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "go-auth-app/models"

	mock "github.com/stretchr/testify/mock"
)

// SocialAccountRepository is an autogenerated mock type for the SocialAccountRepository type
type SocialAccountRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: socialAccount
func (_m *SocialAccountRepository) Create(socialAccount *models.SocialAccount) error {
	ret := _m.Called(socialAccount)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.SocialAccount) error); ok {
		r0 = rf(socialAccount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByProvider provides a mock function with given fields: provider, providerID
func (_m *SocialAccountRepository) FindByProvider(provider string, providerID string) (*models.SocialAccount, error) {
	ret := _m.Called(provider, providerID)

	if len(ret) == 0 {
		panic("no return value specified for FindByProvider")
	}

	var r0 *models.SocialAccount
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*models.SocialAccount, error)); ok {
		return rf(provider, providerID)
	}
	if rf, ok := ret.Get(0).(func(string, string) *models.SocialAccount); ok {
		r0 = rf(provider, providerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SocialAccount)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(provider, providerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSocialAccountRepository creates a new instance of SocialAccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSocialAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *SocialAccountRepository {
	mock := &SocialAccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
